<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Cipher',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
    );
    $items['cipher_output_page'] = array(
        'title' => 'Your ciphered phrase...',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'display_cipher_output',
    );
    return $items;
}

function cipher_form() {
    $form = array();
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Pick a positive integer for your phrase letters to shift.',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'select',
        '#description' => 'Pick a direction for your phrase letters to shift.',
        '#options' => array(
            0 => t('Left'),
            1 => t('Right'),
        ),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Your Phrase',
        '#type' => 'textfield',
        '#description' => 'Enter a phrase to be ciphered. (No special characters outside of spaces or punctuation)',
        '#required' => TRUE,
        // '#element_validate' => ('element_validate_punctuation'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

// function element_validate_punctuation($element) {
//     $special_characters = ("@#$%^&*()_+-=`~[]", "#");
//     if (preg_match("#[{$special_characters}]#"), $element) {
//         form_error($element, t("Phrase cannot contain special characters outside of regular spacing and punctuation."));
//     }
// }

function cipher_form_submit($form, &$form_state) {
    $initial_shift_value = $form_state['values']['shift_value'] % 26;
    $direction = $form_state['values']['direction'];
    if ($direction == 0) {
        $shift_value = -$initial_shift_value;
    } else {
        $shift_value = $initial_shift_value;
    }
    $phrase = strtolower($form_state['values']['phrase']);
    $alphabet = 'abcdefghijklmnopqrstuvwxyz';
    $alphabet_array = array(
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
    );

    $phrase_array = str_split($phrase);
    $cipher_array = array();
    foreach($phrase_array as $character) {
        if(in_array($character, $alphabet_array)) {
            $new_position = strrpos($alphabet, $character) + $shift_value;
            if(($new_position < 26) && ($new_position > -1)) {
                array_push($cipher_array, $alphabet_array[$new_position]);
            } elseif ($new_position < 0) {
                array_push($cipher_array, $alphabet_array[$new_position+26]);
            } elseif ($new_position > 25) {
                array_push($cipher_array, $alphabet_array[$new_position-26]);
            }
        } else {
            array_push($cipher_array, $character);
        }
    }

    $_SESSION['ciphered_phrase'] = implode('', $cipher_array);

    $form_state['redirect'] = 'cipher_output_page';
}

function display_cipher_output() {
    return $_SESSION['ciphered_phrase'];
}
